# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba68fbaf012d3003c15008ec1a8ce4694fb283a7793f88f9f0e073e2eb805d0a24ee07d8ebedcd5ccfa6eb24d157e13a7aa0947fe01196252aaea14f2f517d48

test:
  secret_key_base: 9a6a9bbe66329396e702f9f710e3121abf07cdfadbe887172c0633bae737cddcd6873cc64dda031e5a999d003d56ef24d239e12aca7d84e1aec09aa9db8f02c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
